---

- name: Include vars of vcenter_host.yml
  ansible.builtin.include_vars:
    file: vcenter_host.yml
    name: vcenter

- name: List hosts in ESXi
  debug:
    msg: "Host: {{ item }}"
  loop: "{{ groups['esxi'] }}"

- name: List hosts in VC
  debug:
    msg: "Host: {{ item }}"
  loop: "{{ groups['vc'] }}"

- name: Remove vSphere environment
  block:

    - name: "DELETE virtual machine {{ host_fact_name }} version {{ version }}"
      community.vmware.vmware_guest:
        datacenter: "{{ vcenter.vc_datacenter }}"
        folder: "{{ vcenter.vc_datacenter }}/vm/{{ vcenter.vc_folder }}"
        name: "{{ host_fact_name }}"
        state: absent
        force: true

  when: removevsphere | bool 


