---

#- name: Include vars of host.yml
#  ansible.builtin.include_vars:
#    file: host.yml
#    name: vcenter

- name: List hosts in ESXi
  debug:
    msg: "Host: {{ item }}"
  loop: "{{ groups['esxi'] }}"

- name: List hosts in VC
  debug:
    msg: "Host: {{ item }}"
  loop: "{{ groups['vc'] }}"

- name: Remove vSphere environment
  block:

    - name: "DELETE virtual machine {{ host_fact_name }} version {{ version }}"
      community.vmware.vmware_guest:
        datacenter: "{{ vc_datacenter }}"
        folder: "{{ vc_datacenter }}/vm/{{ vc_folder }}"
        name: "{{ host_fact_name }}"
        state: absent
        force: true

  when: removevsphere | bool 


